Cali_Bus/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", include("core.login.urls")),
    path("admin/", admin.site.urls),
    path("calibus/", include("core.calibus.urls")),
    path("reports/", include("core.reports.urls")),
    path("user/", include("core.user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/calibus/urls.py
from django.urls import path
from core.calibus.views.route.views import *
from core.calibus.views.client.views import *
from core.calibus.views.dashboard.views import *
from core.calibus.views.travel.views import *
from core.calibus.views.parcel.views import *
from core.calibus.views.bus.views import *
from core.calibus.views.remittance.views import *
from core.calibus.views.tests.views import TestView
from core.calibus.views.ticket.views import *

app_name = "calibus"

urlpatterns = [
    # route
    path("route/list/", RouteListView.as_view(), name="route_list"),
    path("route/add/", RouteCreateView.as_view(), name="route_create"),
    path("route/update/<int:pk>/", RouteUpdateView.as_view(), name="route_update"),
    path("route/delete/<int:pk>/", RouteDeleteView.as_view(), name="route_delete"),
    # client
    path("client/list/", ClientListView.as_view(), name="client_list"),
    path("client/add/", ClientCreateView.as_view(), name="client_create"),
    path("client/update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client/delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
    path(
        "client/autocomplete/",
        ClientAutocompleteView.as_view(),
        name="client_autocomplete",
    ),
    # travel
    path("travel/list/", TravelListView.as_view(), name="travel_list"),
    path("travel/add/", TravelCreateView.as_view(), name="travel_create"),
    path("travel/update/<int:pk>/", TravelUpdateView.as_view(), name="travel_update"),
    path("travel/delete/<int:pk>/", TravelDeleteView.as_view(), name="travel_delete"),
    # home
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    # test
    path("test/", TestView.as_view(), name="test"),
    # parcel
    path("parcel/list/", ParcelListView.as_view(), name="parcel_list"),
    path("parcel/add/", ParcelCreateView.as_view(), name="parcel_create"),
    path("parcel/change_status/", change_status, name="parcel_change_status"),
    path(
        "parcel/receipt/pdf/<int:pk>/",
        ParcelReceiptPdfView.as_view(),
        name="parcel_receipt_pdf",
    ),
    # bus
    path("bus/list/", BusListView.as_view(), name="bus_list"),
    path("bus/add/", BusCreateView.as_view(), name="bus_create"),
    path("bus/update/<int:pk>/", BusUpdateView.as_view(), name="bus_update"),
    path("bus/delete/<int:pk>/", BusDeleteView.as_view(), name="bus_delete"),
    # remittance
    path("remittance/list/", RemittanceListView.as_view(), name="remittance_list"),
    path("remittance/add/", RemittanceCreateView.as_view(), name="remittance_create"),
    # ticket
    path("ticket/list/", TravelSaleListView.as_view(), name="travel_sale_list"),
    path("ticket/add/", TicketCreateView.as_view(), name="ticket_create"),
    path(
        "ticket/passenger/pdf/<int:detail_id>/",
        TicketPassengerPdfView.as_view(),
        name="ticket_passenger_pdf",
    ),
    path(
        "ticket/list/pdf/<int:ticket_id>/",
        TicketListPdfView.as_view(),
        name="ticket_list_pdf",
    ),
    path(
        "passenger/list/pdf/<int:travel_id>/",
        PassengerListPdfView.as_view(),
        name="passenger_list_pdf",
    ),
]

core/user/urls.py
from django.urls import path
from core.user.views import *


app_name = "user"

urlpatterns = [
    # user
    path("list/", UserListView.as_view(), name="user_list"),
    path("add/", UserCreateView.as_view(), name="user_create"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
    path("change/group/<int:pk>/", UserChangeGroup.as_view(), name="user_change_group"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path(
        "change/password/",
        UserChangePasswordView.as_view(),
        name="user_change_password",
    ),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
  <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
      <!-- Header -->
      {% include 'vtc/header.html' %}
      <!-- Sidebar -->
      {% include 'vtc/sidebar.html' %}
      <!-- Content -->
      <div class="content-wrapper">
        <div class="content-header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-6">
                <h2 class="m-0 text-dark">Bienvenido <small>{{ request.user.get_full_name }}</small></h2>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item">
                    <a href="{% url 'calibus:dashboard' %}">Home</a>
                  </li>
                  <li class="breadcrumb-item">
                    <a href="{{ list_url }}">{{ entity }}</a>
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="container-fluid">
            {% block content %}

            {% endblock %}
          </div>
        </div>
      </div>
      <!-- Footer -->
      {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
  </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'calibus:dashboard' %}" class="nav-link">Home</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    {% if request.user.groups.all %}
      <li class="nav-item dropdown">
          <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              class="nav-link {% if request.user.groups.all.count > 1 %} dropdown-toggle {% endif %}">{{ request.session.group_name }}</a>
          {% if request.user.groups.all.count > 1 %}
              <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                style="left: 0px; right: inherit;">
              {% for g in request.user.groups.all %}
                {% if g.id != request.session.group_id %}
                  <li><a href="{% url 'user:user_change_group' g.id %}" class="dropdown-item">{{ g.name }} </a></li>
                {% endif %}
              {% endfor %}          
            </ul>
          {% endif %}
      </li>
    {% endif %}
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#"><i class="fas fa-users-cog"></i> {{ request.user.username }}</a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header" style="font-size: 12px;">Sú último acceso fue {{ request.user.last_login }}</span>
        <div class="dropdown-divider"></div>
        <a href="{% url "user:user_profile" %}" class="dropdown-item"><i class="fas fa-edit mr-2"></i> Editar perfil</a>
        <div class="dropdown-divider"></div>
        <a href="{% url "user:user_change_password" %}" class="dropdown-item"><i class="fas fa-lock mr-2"></i> Editar password</a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer"><p>Este sistema te permitira realizar diferentes actividades</p></a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-power-off" aria-hidden="true"></i></a>
    </li>
  </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="{% url 'calibus:dashboard' %}" class="brand-link">
    <img src="{% static 'img/logo.png' %}" alt="CaliBUS Logo" class="brand-image img-circle elevation-3" style="opacity: .8" />
    <span class="brand-text font-weight-light"><b>Cali</b>BUS</span>
  </a>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image" />
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ request.user.username }}</a>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-header">Módulos</li>
        <li class="nav-item has-treeview {% if 'empresa' in parent %} menu-open {% endif %}">
          <a href="#" class="nav-link {% if 'empresa' in parent %} active {% endif %}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Empresa
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'user:user_list' %}" class="nav-link {% if 'usuario' in segment %} active {% endif %}">
                <i class="fas fa-user-friends nav-icon"></i>
                <p>Usuarios</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'calibus:bus_list' %}" class="nav-link {% if 'bus' in segment %} active {% endif %}">
                <i class="fas fa-bus nav-icon"></i>
                <p>Buses</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'calibus:route_list' %}" class="nav-link {% if 'ruta' in segment %} active {% endif %}">
                <i class="fas fa-road nav-icon"></i>
                <p>Rutas</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'calibus:travel_list' %}" class="nav-link {% if 'viaje' in segment %} active {% endif %}">
                <i class="fas fa-map-marked-alt nav-icon"></i>
                <p>Viajes</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="{% url 'calibus:travel_sale_list' %}" class="nav-link {% if 'venta_pasajes' in segment %}active{% endif %}">
            <i class="fas fa-ticket-alt nav-icon"></i>
            <p>Venta de Pasajes</p>
          </a>
        </li>
        
        <li class="nav-item has-treeview {% if 'envios' in parent %} menu-open {% endif %}">
          <a href="#" class="nav-link {% if 'envios' in parent %}active{% endif %}">
            <i class="nav-icon fas fa-exchange-alt"></i>
            <p>
              Envíos
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'calibus:parcel_list' %}" class="nav-link {% if 'encomienda' in segment %} active {% endif %}">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Encomiendas</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'calibus:remittance_list' %}" class="nav-link">
                <i class="nav-icon fas fa-hand-holding-usd"></i>
                <p>Giros</p>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a href="{% url 'calibus:client_list' %}" class="nav-link {% if 'cliente' in segment %}active{% endif %}">
            <i class="nav-icon fas fa-users"></i>
            <p>Clientes</p>
          </a>
        </li>

        <li class="nav-item {% if 'layout' in parent %} menu-open {% endif %}">
          <a href="#" class="nav-link {% if 'layout' in parent %}active{% endif %}">
            <i class="nav-icon fas fa-clipboard-list"></i>
            <p>
              Recibos
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-ticket-alt"></i>
                <p>Pasajes</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-truck-loading"></i>
                <p>Encomiendas</p>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item {% if 'layout' in parent %} menu-open {% endif %}">
          <a href="#" class="nav-link {% if 'layout' in parent %}active{% endif %}">
            <i class="nav-icon fas fa-chart-pie"></i>
            <p>
              Reportes
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-ticket-alt"></i>
                <p>Buses</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Clientes</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'sale_report' %}" class="nav-link">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Pasajes</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Encomiendas</p>
              </a>
            </li>
          </ul>
        </li>
        {% comment %} <li class="nav-item {% if 'layout' in parent %} menu-open {% endif %}">
          <a href="#" class="nav-link {% if 'layout' in parent %}active{% endif %}">
            <i class="nav-icon fas fa-clipboard-list"></i>
            <p>
              Seguridad
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-ticket-alt"></i>
                <p>Accesos</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Grupos</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-dolly"></i>
                <p>Respaldos</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>Ventas</p>
          </a>
        </li> {% endcomment %}
      </ul>
    </nav>
  </div>
</aside>